
# Introduction to Pandas

In [1]:
import numpy as np
import pandas as pd

<H1> DataFrames <H1>
    <i> lets create some data similar to car price data</i>

In [2]:
data = [
    ['Nissan','Stanza',1991,138,4,'MANUAL','Sedan',2000],
    ['Hyundai','Sonata','2017',None,4,'AUTOMATIC','Sedan',27150],
    ['Lotus','Elise',2010,218,4,'MANUAL','CONVERTIBLE',54990],
    ['GMC','Acadia',2017,194,4,'AUTOMATIC','4dr SUV',34450],
    ['Nissan','Frontier',2017,261,6,'MANUAL','Pickup',32340],
]

columns = [
    'Make','Model','Year','Engine HP','Engine Cylinders','Transmission Type','Vehicle style','MSRP'
]

In [3]:
df = pd.DataFrame(data)

In [4]:
df

         0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        Sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  CONVERTIBLE  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [5]:
df = pd.DataFrame(data,columns=columns)

In [6]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
df.head() #quick look at the first few rows of the dataset

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [8]:
df.head(2) # accessing the first two rows of dataset

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [9]:
df.tail(2) #accessing last two rows

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

<H1> Series,Index and Accesing the element</H1>

In [10]:
df.Make #Accessing through dot notation

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [11]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [12]:
df[['Make','Model','MSRP']] #select subsets of column

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [13]:
df[['Engine HP','Transmission Type','Vehicle style']] #use only brackets when accessing column names with spaces
                                                      # or special character

   Engine HP Transmission Type Vehicle style
0      138.0            MANUAL         Sedan
1        NaN         AUTOMATIC         Sedan
2      218.0            MANUAL   CONVERTIBLE
3      194.0         AUTOMATIC       4dr SUV
4      261.0            MANUAL        Pickup

In [14]:
df['id']=['nan1','nan2','nan3','lgm','ijl',] #create new column in dataframe
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000,nan1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,nan2
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990,nan3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,lgm
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,ijl

In [15]:
df['id'] = [1,2,3,4,5] #replacing with new data in 'id' column in dataframe
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [16]:
del df['id'] #delete the 'id' column
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [17]:
df.index  # row identifiers used to align data

RangeIndex(start=0, stop=5, step=1)

In [18]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
df.loc[1] #accessing row 1

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [20]:
dfs = df.sample(frac=1)#randomly suffle all rows
dfs

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [21]:
dfs.loc[[0,1]] #accessing by their index label

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [22]:
dfs.iloc[[0,1]] #accessing by their position

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [23]:
dfs.iloc[[1,2,4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [24]:
dfs.reset_index(drop = True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
0,Lotus,Elise,2010,218.0,4,MANUAL,CONVERTIBLE,54990
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
3,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

<H1>Element Wise Operations</H1>

In [25]:
dfs['Engine HP']/100

2    2.18
1     NaN
4    2.61
0    1.38
3    1.94
Name: Engine HP, dtype: float64

In [26]:
dfs['Engine HP']*2

2    436.0
1      NaN
4    522.0
0    276.0
3    388.0
Name: Engine HP, dtype: float64

<H1>Filtering</H1>

In [27]:
dfs.dtypes

Make                  object
Model                 object
Year                  object
Engine HP            float64
Engine Cylinders       int64
Transmission Type     object
Vehicle style         object
MSRP                   int64
dtype: object

In [28]:
dfs['Year'] = pd.to_numeric(dfs['Year'])

In [29]:
dfs['Year'] >= 2015

2    False
1     True
4     True
0    False
3     True
Name: Year, dtype: bool

In [30]:
dfs['Make'] == 'Nissan'

2    False
1    False
4     True
0     True
3    False
Name: Make, dtype: bool

In [31]:
dfs[(dfs["Make"]=="Nissan")& (dfs["Year"]>=2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

<b1>String Operations</b1>

In [32]:
dfs['Vehicle style'].str.lower()

2    convertible
1          sedan
4         pickup
0          sedan
3        4dr suv
Name: Vehicle style, dtype: object

<H1>Summarizing Operations</H1>

In [33]:
dfs.MSRP.min()

2000

In [34]:
dfs.MSRP.max()

54990

In [35]:
dfs.MSRP.mean()

np.float64(30186.0)

In [36]:
dfs.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [37]:
dfs.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [38]:
dfs.Make.nunique() #unique values in column

4

In [39]:
dfs.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle style        4
MSRP                 5
dtype: int64

<b1>Missing Values</b1>

In [40]:
dfs.isnull() #checks which values is missing

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle style,MSRP
2,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False
0,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False

In [41]:
dfs.isnull().sum() #counts how many values exist

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle style        0
MSRP                 0
dtype: int64

<H1>Grouping</H1>.
groupby() is used to group rows that share the same value in a column, usually to apply an aggregation like sum, mean etc.

In [42]:
dfs.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [43]:
dfs.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

In [44]:
dfs.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [45]:
dfs.MSRP.values

array([54990, 27150, 32340,  2000, 34450])

In [46]:
dfs.to_dict(orient = 'records') #converts dataframe to dictionary

[{'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle style': 'CONVERTIBLE',
  'MSRP': 54990},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle style': 'Pickup',
  'MSRP': 32340},
 {'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle style': 'Sedan',
  'MSRP': 2000},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle style': '4dr SUV',
  'MSRP': 34450}]